---
apiVersion: v1
kind: Namespace
metadata:
  name: go-game
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-game
  name: go-datetime-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-datetime-app
  replicas: 2  
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-datetime-app
    spec:
      containers:
      - image: saihemanth02/go-datetime-app:latest  
        imagePullPolicy: Always
        name: go-datetime-app
        ports:
        - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  namespace: go-game
  name: go-datetime-service
spec:
  ports:
    - port: 8080  # Using the port exposed by the application
      targetPort: 8080
      protocol: TCP
  type: NodePort  # 
  selector:
    app.kubernetes.io/name: go-datetime-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: go-game
  name: go-datetime-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: go-datetime-service
              port:
                number: 8080  # Match the service port

